DSL
ZeLebo/OOP pull request #11
Opened 2022-06-05 16:50 UTC by ZeLebo

2022-06-07 12:08 UTC, Leidenn2509 requested changes

2022-06-07 12:08 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +        }
Объект группы нужно создать отдельно, а студентам просто присваивать номер
`group = "20214"`

2022-06-07 12:09 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +        }
Ну сделаем, что уж теперь)

2022-06-14 08:34 UTC, ZeLebo commented
Need to runaway, so only building HTML left, but I also made a console output for all the stuff

2022-06-14 08:37 UTC, ZeLebo commented
The model itself has changed a little bit: Groups are now avaliable and all the data is collected from the kts files (lying in `config` package)
All reports are generated in the `report` package

2022-06-14 08:38 UTC, ZeLebo commented
To be honest, don't wanna create beautiful HTML, wanna just copy past the stuff going to terminal, cuz I love it

2022-06-14 15:19 UTC, Leidenn2509 requested changes
А что в `bin/main` лежит?

2022-06-14 15:19 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +    val student = student {
?

2022-06-14 15:19 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +// TODO: conf data from files, not hard code
Очень хочется

2022-06-14 15:19 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +DSL().groups {
`DSL().` не должно быть
Почему бы просто не предоставить пользователю метод `group`?

2022-06-14 15:19 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +DSL().groups {
Да и вообще вроде же поняли, что тут рекурсия. Надо чинить

2022-06-14 15:19 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +            student {
Уже говорил, что группы и студенты не вложенные структуры.
Отдельно описываете группу, отдельно студентов

2022-06-14 15:37 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +    val student = student {
Это было для теста

2022-06-14 15:40 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +DSL().groups {
Ну рекурсии тут уже нет, спасибо фишкам kotlin
А предоставить метод group - предоставляется метод groups и да, для работы скрипта он должен быть где-то описан
... Возможно, я тупой...

2022-06-14 15:43 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +    val student = student {
Надо удалить

2022-06-14 15:43 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +// TODO: conf data from files, not hard code
`val textConfig = File("./src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts").readText()` вроде всё ещё хардкод

2022-06-14 15:45 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +DSL().groups {
Её нет, но lazy это просто костыль в данном случае, проблему он не решил. У вас циклическая инициализация в самой логике класса

2022-06-14 15:46 UTC, Leidenn2509 commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +            student {
Такое ТЗ. Предполагается, что можно создать группу, а потом отдельно, произвольно накидывать студентов

2022-06-14 15:52 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +// TODO: conf data from files, not hard code
Ну так он в runtime запускает kts скрипт и оттуда читает данные, которые можно менять
А комментарий был к тому времени, когда скриптов не было)

2022-06-14 15:52 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +DSL().groups {
Ладно, тогда исправлю

2022-06-14 15:53 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +            student {
Да блин, неприятненько

2022-06-14 15:53 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +    val student = student {
Понял

2022-06-14 15:56 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/dsl/DSL.kt
> +// TODO: conf data from files, not hard code
Вы об этом...
А как...
...

2022-06-14 17:39 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +DSL().groups {
Done

2022-06-14 17:39 UTC, ZeLebo commented on Task_2_4_1/src/main/kotlin/ru/nsu/sartakov/configs/GroupConf.kts
> +            student {
Done

2022-06-14 17:41 UTC, ZeLebo commented
> А что в `bin/main` лежит?

Это штука, без которой не работают скрипты)

2022-06-15 15:48 UTC, Leidenn2509 approved these changes

2022-06-15 15:53 UTC, merged