The calculator lab
ZeLebo/OOP pull request #3
Opened 2021-11-01 16:15 UTC by ZeLebo

I'm pulling right from the IDEA
There's one problem. I wanted to use "switch-case", but the version of the language doesn't support it yet, so look at the ugly version of "if-else if-else")))

2021-11-08 13:47 UTC, Leidenn2509 requested changes
Нет документации

2021-11-08 13:47 UTC, Leidenn2509 commented on Calculator/src/main/java/Operations/AddOperator.java
> +package Operations;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-11-08 13:47 UTC, Leidenn2509 commented on Calculator/src/main/java/ru/nsu/sartakov/Calculator.java
> +        List<Operation> lst = OperationFabric.produceOperations();
Пожалуйста отдайте `i`.

2021-11-08 13:47 UTC, Leidenn2509 commented on Calculator/src/main/java/ru/nsu/sartakov/Calculator.java
> +        }
Фабрика должна быть единственной кто знает что-то про операции. Перенесите это в фабрику, создайте фабричный метод и будет супер.

2021-11-08 13:47 UTC, Leidenn2509 commented on Calculator/src/main/java/ru/nsu/sartakov/Calculator.java
> +    }
Лучше вынести это в отдельный класс. Отделить интерактив от калькулятора

2021-11-08 13:47 UTC, Leidenn2509 commented on Calculator/src/main/java/Operations/AddOperator.java
> +package Operations;
А ещё это должен быть под пакет вашего основного пакета

2021-11-09 02:58 UTC, ZeLebo commented
In this patch you can admire our great documentation

2021-11-09 08:08 UTC, Leidenn2509 requested changes

2021-11-09 08:08 UTC, Leidenn2509 commented on Calculator/src/main/java/ru/nsu/sartakov/OperationFabric.java
> +    public Map<String, Operation> getOperations() {
Фабричный метод

2021-11-09 08:08 UTC, Leidenn2509 commented on Calculator/src/main/java/ru/nsu/sartakov/OperationFabric.java
> +    public Map<String, Operation> getOperations() {
```java
public Operation getOperation(String symbol) {
    return opeartions[symbol];
}
```

2021-11-09 13:53 UTC, Leidenn2509 approved these changes

2021-11-09 13:53 UTC, Leidenn2509 commented on Calculator/src/main/java/ru/nsu/sartakov/OperationFabric.java
> +    }
Я бы всё таки предпочел метод возвращающий операцию, но и так можно

2021-11-09 13:53 UTC, merged