New labs
ZeLebo/OOP pull request #4
Opened 2021-11-17 00:47 UTC by ZeLebo

2021-11-17 00:47 UTC, ZeLebo commented
Мне самому больно на это смотреть, я могу сказать, что это большой заготовка

2021-11-17 00:47 UTC, ZeLebo commented
Вот поэтому я и просил сместить дедлайн…

2021-11-18 12:45 UTC, Leidenn2509 requested changes
- Просочились файлы из других лаб
- Работа с консолью

2021-11-18 12:45 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Note.java
> +    private String creationTime;
`LocalDateTime`

2021-11-18 12:45 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Note.java
> +public class Note {
Ещё название добавьте

2021-11-18 12:45 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +    DateTimeFormatter dtf;
private

2021-11-18 12:45 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +    DateTimeFormatter dtf;
Назовите переменную понятнее

2021-11-18 12:45 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +        }
Используйте `stream`

2021-11-18 12:45 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +        }
Вынесите это из notebook, чтобы им можно было пользоваться и без доступа к файловой системе

2021-11-25 04:54 UTC, ZeLebo commented
Тут траблы с jar

2021-11-25 04:55 UTC, ZeLebo commented
Я не понимаю, почему он криво собирается, типа, что-то с ним не так, а что именно -> билдит аппу не так

2021-11-25 05:23 UTC, ZeLebo commented
Everything's gonna work

2021-11-25 11:16 UTC, Leidenn2509 requested changes

2021-11-25 11:16 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Json.java
> +    transient DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("d.M.yyyy HH:mm:ss");
- Почему transient? 
- private

2021-11-25 11:16 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Json.java
> +    Gson gson = new GsonBuilder()
private

2021-11-25 11:16 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Json.java
> +            System.out.println("The file hasn't been found");
Нехорошо ловить исключение и просто печатать его в консоль. Потому что
- Пользователю не очень интересно читать стектрейс
- Никто сверху не узнает (в этом случае `Notebook`), что что-то сломалось

2021-11-25 11:16 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Json.java
> +
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

2021-11-25 11:16 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/App.java
> +    public static void main(String[] args) throws IOException, ParseException {
Разбейте main на методы

2021-11-25 11:16 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/App.java
> +        Options options = new Options();
Ещё бы `help`, а то непонятно как использовать программу не заглядывая в код

2021-11-25 18:00 UTC, ZeLebo commented
Замечания исправил ( где-то просто уже поплыл и получились ошибки ( но не ошибки ))

2021-11-29 13:08 UTC, Leidenn2509 requested changes

2021-11-29 13:08 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +            System.out.println("The file wasn't found");
Вашу записную книжку могут использовать и не в консольном приложении. Не стоит тут печатать в консоль

2021-11-29 13:08 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +    public List<Note> findNotesPeriodSwords(LocalDateTime from, LocalDateTime to, List<String> subWords) throws IOException {
Swords?

2021-11-29 14:20 UTC, ZeLebo commented on Task_1_4_2/src/main/java/ru/nsu/sartakov/Notebook.java
> +    public List<Note> findNotesPeriodSwords(LocalDateTime from, LocalDateTime to, List<String> subWords) throws IOException {
Ну IDEA так захотела…

2021-11-30 08:29 UTC, Leidenn2509 approved these changes

2021-11-30 08:29 UTC, merged