Task_2_1_1
ZeLebo/OOP pull request #7
Opened 2022-02-18 15:04 UTC by ZeLebo

I need to make one more task till, so that's all
Some strange things happen, when running this code, threads are supossed to be working much faster, maybe I don't understand something

2022-02-21 09:51 UTC, Leidenn2509 requested changes
А я не могу запустить вашу лабу

2022-03-02 08:36 UTC, Leidenn2509 requested changes
- Вы выполняете противоположную задачу
- Нет графика

2022-03-02 08:36 UTC, Leidenn2509 commented on Task_2_1_1/src/main/java/ru/nsu/sartakov/ThreadChecker.java
> +        final int ID;
Зачем тут ID?

2022-03-02 08:36 UTC, Leidenn2509 commented on Task_2_1_1/src/main/java/ru/nsu/sartakov/TimeChecker.java
> +        long startTime, endTime;
code style

2022-03-02 08:36 UTC, Leidenn2509 commented on Task_2_1_1/src/main/java/ru/nsu/sartakov/TimeChecker.java
> +        System.out.println("The time elapsed: " + (endTime - startTime) / 50 + " nanoseconds\n");
51?

2022-03-02 08:36 UTC, Leidenn2509 commented on Task_2_1_1/src/main/java/ru/nsu/sartakov/TimeChecker.java
> +        }
А зачем?

2022-03-03 15:22 UTC, ZeLebo commented
Как говорится, я наshitкодил, а вам проверять))) 😅

2022-03-10 10:24 UTC, Leidenn2509 approved these changes

2022-03-10 10:24 UTC, merged