Lab2 2
ZeLebo/OOP pull request #8
Opened 2022-03-14 06:19 UTC by ZeLebo

**Raw laba not to be kicked**

2022-03-21 19:02 UTC, Leidenn2509 requested changes
+ Тесты

2022-03-21 19:02 UTC, Leidenn2509 commented on Task_2_1_2/src/main/java/ru/nsu/sartakov/Consumer.java
> +public class Consumer implements Runnable{
Кто такой консьюмер и как он связан с пекарем или доставщиком?

2022-03-21 19:02 UTC, Leidenn2509 commented on Task_2_1_2/src/main/java/ru/nsu/sartakov/Employees.java
> +public class Employees {
А точно нужно выделять это в отдельный класс?

2022-04-01 03:16 UTC, ZeLebo commented
SOLID:
- Каждый объект выплоняет только одну обязанность и является единственным представителем класса
- Толстых интерфейсов просто нет
- Конфигурация объектов происходит через изолированный от основной программы модули

На самом деле, намного интереснее осознавать принципы SOLID на нормальном **Расширяемом в данный момент проекте**. Пишем командой сервер и уже пришлось почти полностью всё переписать, потому что как показывает практика - это самый адекватный и безболезненный вариант что-то быстро поменять в проекте - придерживаться хотя бы пары буков из пресловутого SOLID. (Репозиторий открытый, можете даже посмотреть)

2022-04-12 00:44 UTC, Leidenn2509 approved these changes

2022-04-12 00:44 UTC, merged